language: java
before_install:
  - chmod +x mvnw
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients:
      - mig29mig29@gmail.com
    on_success: always # default: change /never
    on_failure: always # default: always